# Generated by Django 5.1.7 on 2025-03-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_worker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
