# Generated by Django 5.1.7 on 2025-03-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_worker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='name',
        ),
    ]
