# Generated by Django 5.1.7 on 2025-03-29 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_cleanedphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CleanedPhoto',
        ),
    ]
